# Generated by Django 3.2.9 on 2021-11-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='controller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=20, unique=True, verbose_name='mark')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('type', models.CharField(max_length=20, verbose_name='type')),
                ('introduce', models.CharField(max_length=20, verbose_name='introduce')),
            ],
        ),
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=20, unique=True, verbose_name='mark')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('measure', models.CharField(max_length=20, verbose_name='measure')),
                ('type', models.CharField(max_length=20, verbose_name='type')),
                ('group', models.CharField(max_length=20, verbose_name='group')),
                ('x', models.CharField(max_length=20, verbose_name='x')),
                ('p', models.CharField(max_length=20, verbose_name='p')),
                ('min', models.CharField(max_length=20, verbose_name='min')),
                ('max', models.CharField(max_length=20, verbose_name='max')),
                ('alarm', models.CharField(max_length=20, verbose_name='alarm')),
                ('time', models.CharField(max_length=20, verbose_name='time')),
                ('introduce', models.CharField(max_length=20, verbose_name='introduce')),
            ],
        ),
    ]
