# Generated by Django 3.2.9 on 2021-11-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_sensor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='time'),
        ),
    ]
