# Generated by Django 3.2.9 on 2021-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_sensor_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='update'),
        ),
    ]
