# Generated by Django 3.2.9 on 2021-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_sensor_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time')),
                ('level', models.CharField(max_length=20, verbose_name='level')),
                ('cause', models.CharField(max_length=20, verbose_name='cause')),
                ('state', models.CharField(max_length=20, verbose_name='state')),
            ],
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time')),
                ('mark', models.CharField(max_length=20, verbose_name='mark')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('data', models.CharField(max_length=20, verbose_name='data')),
                ('group', models.CharField(max_length=20, verbose_name='group')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('introduce', models.CharField(max_length=80, verbose_name='introduce')),
            ],
        ),
        migrations.AlterField(
            model_name='controller',
            name='introduce',
            field=models.CharField(max_length=80, verbose_name='introduce'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='introduce',
            field=models.CharField(max_length=80, verbose_name='introduce'),
        ),
    ]
