# Generated by Django 3.2.9 on 2021-11-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20211121_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('order', models.CharField(max_length=300, verbose_name='order')),
                ('introduce', models.CharField(max_length=80, verbose_name='introduce')),
            ],
        ),
    ]
