# Generated by Django 3.2.9 on 2021-11-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('order', models.CharField(max_length=300, verbose_name='order')),
                ('time', models.DateTimeField(verbose_name='time')),
            ],
        ),
    ]
