# Generated by Django 3.2.9 on 2021-11-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='time',
            field=models.CharField(max_length=300, verbose_name='time'),
        ),
    ]
