# Generated by Django 3.2.9 on 2021-11-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_plan_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='trigger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor', models.CharField(max_length=20, verbose_name='sensor')),
                ('c1', models.CharField(max_length=300, verbose_name='c1')),
                ('c2', models.CharField(max_length=300, verbose_name='c2')),
                ('send', models.CharField(max_length=300, verbose_name='send')),
                ('order', models.CharField(max_length=300, verbose_name='order')),
                ('mintime', models.CharField(max_length=300, verbose_name='mintime')),
                ('introduce', models.CharField(max_length=80, verbose_name='introduce')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='time')),
            ],
        ),
    ]
