# Generated by Django 3.2.9 on 2021-11-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_order_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='cause',
            field=models.CharField(max_length=80, verbose_name='cause'),
        ),
    ]
