# Generated by Django 3.2.9 on 2021-11-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_alarm_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time'),
        ),
    ]
